name: android
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.8.0 --quiet
          haxelib install flixel-addons 3.3.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install extension-androidtools 2.1.1 --quiet
          haxelib git hscript https://github.com/kivers9k/hscript.git master --quiet
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git main --quiet
          haxelib list
      
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
     
      - name: Compile
        run: |
          haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
 
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: outputBuild
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
