name: android
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
 
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/beihu235/hxcpp.git master
          haxelib install lime 8.1.1
          haxelib install openfl 9.3.3
          haxelib install flixel 5.5.0
          haxelib install flixel-addons 3.3.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install extension-androidtools 2.1.1
          haxelib git hscript https://github.com/kivers9k/hscript.git master
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git main
          haxelib list
      
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: |
          haxelib run lime build android
 
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: outputBuild
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
